import * as fs from 'fs/promises';
import * as path from 'path';
import { Logger } from '../utils/logger';

export interface MCPConfig {
  endpoint: string;
  transport: {
    type: 'streamable_http' | 'stdio';
    port?: number;
  };
  introspection: {
    introspect: {
      enabled: boolean;
    };
    search: {
      enabled: boolean;
    };
    execute: {
      enabled: boolean;
    };
  };
  schema?: {
    source: 'local' | 'introspection';
    path?: string;
  };
  headers?: Record<string, string>;
}

export interface ClaudeDesktopConfig {
  mcpServers: {
    [key: string]: {
      command: string;
      type?: 'stdio' | 'sse' | 'streamable_http';
      args: string[];
      env?: Record<string, string>;
    };
  };
}

export class MCPConfigGenerator {
  /**
   * Generate MCP Server configuration
   */
  static async generateConfig(
    outputDir: string,
    serverPort: number = 4000,
    datasourceName: string = 'graphql'
  ): Promise<void> {
    const schemaPath = path.join(outputDir, 'schema.graphql');

    // Check if schema exists
    try {
      await fs.access(schemaPath);
    } catch {
      Logger.warning('Schema file not found. Make sure to run generate first.');
      return;
    }

    const endpoint = `http://localhost:${serverPort}/`;

    const mcpConfig: MCPConfig = {
      endpoint,
      transport: {
        type: 'streamable_http',
        port: 8000
      },
      introspection: {
        introspect: {
          enabled: true
        },
        search: {
          enabled: true
        },
        execute: {
          enabled: true
        }
      },
      schema: {
        source: 'local',
        path: path.resolve(schemaPath)
      }
    };

    // Generate YAML config (for reference and future use)
    const yamlContent = this.generateYAML(mcpConfig);
    const configPath = path.join(outputDir, 'mcp-config.yaml');
    await fs.writeFile(configPath, yamlContent, 'utf8');

    Logger.success(`MCP config generated: ${configPath}`);

    // Generate .env file for mcp-graphql
    await this.generateEnvFile(outputDir, endpoint);

    // Generate Claude Desktop config snippet
    await this.generateClaudeConfig(outputDir, endpoint, datasourceName);
  }

  /**
   * Generate .env file for mcp-graphql server
   */
  private static async generateEnvFile(
    outputDir: string,
    endpoint: string
  ): Promise<void> {
    const envContent = `# MCP GraphQL Server Environment Variables
# Auto-generated by Apollo Subgraph Generator

ENDPOINT=${endpoint}
ALLOW_MUTATIONS=false

# Optional: Add authentication headers if needed
# HEADERS={"Authorization": "Bearer YOUR_TOKEN"}
`;

    const envPath = path.join(outputDir, '.env.mcp');
    await fs.writeFile(envPath, envContent, 'utf8');
    Logger.success(`MCP environment file generated: ${envPath}`);
  }

  /**
   * Generate YAML content from config object
   */
  private static generateYAML(config: MCPConfig): string {
    const lines: string[] = [
      '# Apollo MCP Server Configuration',
      '# Auto-generated by Apollo Subgraph Generator',
      '# This file is automatically regenerated when schema changes',
      '',
      `endpoint: ${config.endpoint}`,
      '',
      'transport:',
      `  type: ${config.transport.type}`,
    ];

    if (config.transport.port) {
      lines.push(`  port: ${config.transport.port}`);
    }

    lines.push(
      '',
      'introspection:',
      '  introspect:',
      `    enabled: ${config.introspection.introspect.enabled}`,
      '  search:',
      `    enabled: ${config.introspection.search.enabled}`,
      '  execute:',
      `    enabled: ${config.introspection.execute.enabled}`
    );

    if (config.schema) {
      lines.push(
        '',
        'schema:',
        `  source: ${config.schema.source}`
      );
      if (config.schema.path) {
        lines.push(`  path: ${config.schema.path}`);
      }
    }

    if (config.headers && Object.keys(config.headers).length > 0) {
      lines.push('', 'headers:');
      Object.entries(config.headers).forEach(([key, value]) => {
        lines.push(`  ${key}: "${value}"`);
      });
    }

    lines.push('');
    return lines.join('\n');
  }

  /**
   * Generate Claude Desktop configuration snippet
   */
  private static async generateClaudeConfig(
    outputDir: string,
    endpoint: string,
    datasourceName: string
  ): Promise<void> {
    const serverName = `graphql-${datasourceName}`;

    const claudeConfig: ClaudeDesktopConfig = {
      mcpServers: {
        [serverName]: {
          command: 'npx',
          type: 'stdio',
          args: ['-y', 'mcp-graphql'],
          env: {
            ENDPOINT: endpoint,
            ALLOW_MUTATIONS: 'false'
          }
        }
      }
    };

    const configPath = path.join(outputDir, 'claude-desktop-config.json');
    await fs.writeFile(
      configPath,
      JSON.stringify(claudeConfig, null, 2),
      'utf8'
    );

    Logger.success(`Claude Desktop config snippet generated: ${configPath}`);
    Logger.info('\nTo use with Claude Desktop, add this to your claude_desktop_config.json:');
    Logger.info(JSON.stringify(claudeConfig, null, 2));
  }

  /**
   * Check if apollo-mcp-server is installed globally
   */
  private static async checkMCPServerInstalled(): Promise<boolean> {
    try {
      const { execSync } = require('child_process');
      execSync('which apollo-mcp-server', { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Generate standalone MCP server startup script
   */
  static async generateStartupScript(
    outputDir: string,
    serverPort: number = 4000
  ): Promise<void> {
    const scriptContent = `#!/bin/bash
# Auto-generated MCP Server Startup Script
# This script starts the mcp-graphql server with the generated configuration

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.mcp"
ENDPOINT="http://localhost:${serverPort}/"

echo "Starting MCP GraphQL Server..."
echo "GraphQL Endpoint: $ENDPOINT"
echo ""

# Load environment variables from .env.mcp
if [ -f "$ENV_FILE" ]; then
    export $(cat "$ENV_FILE" | grep -v '^#' | xargs)
    echo "Loaded config from: $ENV_FILE"
else
    export ENDPOINT="$ENDPOINT"
    export ALLOW_MUTATIONS="false"
    echo "Using default configuration"
fi

echo ""
echo "Starting mcp-graphql server..."
echo "Press Ctrl+C to stop"
echo ""

# Start the MCP server
npx -y mcp-graphql
`;

    const scriptPath = path.join(outputDir, 'start-mcp-server.sh');
    await fs.writeFile(scriptPath, scriptContent, 'utf8');

    // Make script executable
    await fs.chmod(scriptPath, 0o755);

    Logger.success(`MCP startup script generated: ${scriptPath}`);
  }

  /**
   * Update MCP config when server port changes
   */
  static async updateEndpoint(
    outputDir: string,
    serverPort: number
  ): Promise<void> {
    const configPath = path.join(outputDir, 'mcp-config.yaml');

    try {
      const content = await fs.readFile(configPath, 'utf8');
      const updated = content.replace(
        /endpoint: http:\/\/localhost:\d+\//,
        `endpoint: http://localhost:${serverPort}/`
      );
      await fs.writeFile(configPath, updated, 'utf8');
      Logger.info(`MCP config updated with new endpoint port: ${serverPort}`);
    } catch (error) {
      // Config doesn't exist yet, skip update
    }
  }
}
